Basic home page (without map and info about supermarkets)
SHvatov/DiscountsNearby pull request #4
Opened 2020-11-19 19:32 UTC by MarchenkoVladislav

![image](https://user-images.githubusercontent.com/44652081/99714486-b12f1780-2ab6-11eb-8c56-7e93d323e193.png)
The first button in navbar is in pushed condition and others no.

2020-11-21 08:32 UTC, SHvatov reviewed
Page looks pretty normal to me, but maybe we should increase the padding between the buttons on the nav bar?

2020-11-21 08:32 UTC, SHvatov commented on src/main/kotlin/com/discounts/nearby/controller/HomeController.kt
> +    fun homePage() : String = "/homePage"
In order to maintain the readability of the code and also single common style, please, when you are committing changes in IDEA, check this options as well:
![Screenshot from 2020-11-21 11-27-49](https://user-images.githubusercontent.com/15994914/99871609-171dbb00-2bed-11eb-89c6-631ff58e3d29.png)

2020-11-21 08:35 UTC, SHvatov commented
And  also, lets make the font size of the text in the nav bar bigger, so that it differs from regular text

2020-11-21 08:37 UTC, SHvatov requested changes
Everything else is ok, so after these small fixes I will merge this request right away

2020-11-21 10:17 UTC, SHvatov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add basic template of main page and controller for returning this page](https://trello.com/c/Pb76f4Al/20-add-basic-template-of-main-page-and-controller-for-returning-this-page)

2020-11-23 00:02 UTC, MarchenkoVladislav commented
New version of home page
![image](https://user-images.githubusercontent.com/44652081/99920975-4ee54980-2d38-11eb-8fd0-34644a5513a1.png)

2020-11-23 18:47 UTC, SHvatov approved these changes

2020-11-23 18:47 UTC, merged