Add mail service support
SHvatov/DiscountsNearby pull request #5
Opened 2020-11-20 18:50 UTC by MarchenkoVladislav

2020-11-21 10:13 UTC, SHvatov commented
Modified tests a little. I suggest we use JUnit 5, instead of 4 and its extensions and so on, because they are more useful and can be easily reused or configured the way we want it to be.

2020-11-21 10:15 UTC, SHvatov requested changes

2020-11-21 10:15 UTC, SHvatov commented on src/test/kotlin/com/discounts/nearby/config/MailServiceTestConfig.kt
> +package com.discounts.nearby.config
Modified by SHvatov, see comments

2020-11-21 10:15 UTC, SHvatov commented on src/test/kotlin/com/discounts/nearby/config/extension/SmtpMailServerExtension.kt
> +package com.discounts.nearby.config.extension
Modified by SHvatov, see comments

2020-11-21 10:15 UTC, SHvatov commented on src/test/kotlin/com/discounts/nearby/service/MailServiceTest.kt
> +package com.discounts.nearby.service
Modified by SHvatov, see comments

2020-11-21 10:15 UTC, SHvatov commented on src/test/resources/application-test.properties
> +
Deleted properties cause they are not useful at the moment

2020-11-21 10:17 UTC, SHvatov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add support for the mail services](https://trello.com/c/lcNQ0B3Q/10-add-support-for-the-mail-services)

2020-11-23 00:20 UTC, MarchenkoVladislav commented
I fixed code by your recommendations.

2020-11-23 18:49 UTC, SHvatov approved these changes

2020-11-23 18:49 UTC, merged